# Site settings
title: System-on-Chip Design & Verification
author:
  name: James Donnellan
  email: G00434671@atu.ie
description: "My SOC fgpa-vga-verilog project"

# Build settings
remote_theme: jekyll/minima
